feat: 검색으로 채팅방 조회
geezers-io/Stock2U-api pull request #46
Opened 2023-10-29 16:45 UTC by HyukJunJi

## Type
- [x] Feature
- [ ] Fix

Implements [issue SU-101](https://geezers-io.atlassian.net/browse/SU-101)

## What & Why
검색으로 채팅방 조회하는 API 작성하였습니다.
![image](https://github.com/geezers-io/Stock2U-api/assets/82084599/3b637569-123c-4eea-8273-306acdc4bc34)
이 방식으로 포함된 글자가 있는 채팅방을 가져오도록하였습니다.

## Checklist
- [x] 지라 티켓이 있다면 이슈 번호를 매핑하셨나요?

2023-10-29 23:33 UTC, galaxy4276 commented
[의견]
채팅방 조회 와 검색으로 채팅방 조회 API 가 둘로 나뉘게 된 상황인건가요?
둘이 합칠 수 있을것같아요.
(URL Parameter 기반 조회 )

2023-10-30 07:30 UTC, HyukJunJi commented
넵 두개 나눠서 하게되었습니다.
합칠려면 
![image](https://github.com/geezers-io/Stock2U-api/assets/82084599/f477fac4-cb04-4317-9f1f-d33014ee79e8)
![image](https://github.com/geezers-io/Stock2U-api/assets/82084599/00727c15-75be-4e84-bf0a-80b263bf85bf)
이거 두개 어노테이션 
@GetMapping(/reservations/{title}) 이런식으로 하고 
매개변수로 @RequestParam으로 title 받으면 되나요?

2023-10-30 07:48 UTC, JinkyuByeon approved these changes, later dismissed

2023-10-30 08:57 UTC, galaxy4276 requested changes
개선여지가 보이는 코드에 대해 리뷰하였습니다.

2023-10-30 08:57 UTC, galaxy4276 commented on src/main/java/com/hack/stock2u/chat/api/ReservationApi.java
> +    }
if..else 에 의한 로직에 대한 문제를 해결할 수 있는 여지가 보여요.
* 일부 로직이 두번 중복 됨
* if .. else .. 에 의한 가독성 저하

2023-10-30 08:57 UTC, galaxy4276 commented on src/main/java/com/hack/stock2u/chat/dto/response/SimpleReservation.java
> +    String title,
상품 제목을 말씀하신 것 맞나요? 
(상품 이름대로라면 name 혹은 productName 이 맞음)

2023-10-30 08:57 UTC, galaxy4276 commented on src/main/java/com/hack/stock2u/chat/service/ReservationService.java
> +  }
if 구문 개당 return 으로 코드를 끝내고 있으니 else if .. else 로 연결해주지 않아도 될것 같아요.
(가독성 향상)

2023-10-30 08:58 UTC, galaxy4276 commented
> 넵 두개 나눠서 하게되었습니다. 합칠려면 ![image](https://user-images.githubusercontent.com/82084599/278968690-f477fac4-cb04-4317-9f1f-d33014ee79e8.png) ![image](https://user-images.githubusercontent.com/82084599/278968724-00727c15-75be-4e84-bf0a-80b263bf85bf.png) 이거 두개 어노테이션 @GetMapping(/reservations/{title}) 이런식으로 하고 매개변수로 @RequestParam으로 title 받으면 되나요?


`GetMapping("/reservations")

이후 `@RequestParam` 으로 받아내면 될 것 같습니다.

2023-10-30 09:01 UTC, HyukJunJi commented on src/main/java/com/hack/stock2u/chat/dto/response/SimpleReservation.java
> +    String title,
헷갈리는게 figma보니깐 검색에는 title이 사용되는거 같더라고요 그래서 title로 수정했는데 productTitle로 수정하는게 맞겠죠?

2023-10-30 09:07 UTC, galaxy4276 commented on src/main/java/com/hack/stock2u/chat/dto/response/SimpleReservation.java
> +    String title,
위에 스키마 description 에서 "상품 이름" 으로 되어있어서 여쭤봤어요!
그러면 description 만 수정해주시면 될 것 같습니다.

(잔여재고 항목에 게시글 제목과 상품이름 필드가 존재하여 혼동 여지가 있음)

2023-10-30 09:09 UTC, HyukJunJi commented on src/main/java/com/hack/stock2u/chat/service/ReservationService.java
> +  }
`if (role.equals(UserRole.SELLER.getName())) {
      return reservationRepository.findBySellerId(id, pageable).getContent();
    } else {
      return reservationRepository.findByPurchaserId(id, pageable).getContent();
    }` 이렇게 하면 될까요?

2023-10-30 09:21 UTC, HyukJunJi commented
### fix
기존 reservation에 name이 사용되지 않을것 같아서 title로 수정하였습니다.
![image](https://github.com/geezers-io/Stock2U-api/assets/82084599/cabbbfb1-07c0-4ee0-9813-606467e2b580)
잔여 재고 이름-> 게시글 제목
중복 코드 줄이고자 삼항연산자로 코드 작성했습니다
![image](https://github.com/geezers-io/Stock2U-api/assets/82084599/683108d6-26fb-4c9c-8553-b73426401b27)
```java
private List<Reservation> checkSellerAndPurchaser(Long id, String role, Pageable pageable) {
    return (role.equals(UserRole.SELLER.getName()))
        ? reservationRepository.findBySellerId(id, pageable).getContent() :
        reservationRepository.findByPurchaserId(id, pageable).getContent();
  }
```
```java
private List<Reservation> checkAndSearchSellerAndPurchaser(Long id, String role,
                                                             Pageable pageable, String title) {
    return role.equals(UserRole.SELLER.getName())
        ? reservationRepository.findByTitleContainingAndSellerId(title, id, pageable).getContent() :
        reservationRepository.findByTitleContainingAndPurchaserId(title, id, pageable).getContent();

  }
```

2023-10-30 09:36 UTC, galaxy4276 approved these changes
여기서 더 좋은 코드를 작성해본다면
db 조회코드를 하나로 추상화하는 작업을 수행하면 좋을듯싶어요.
( DB 조회 역할을 책임지는 계층 외에 타 계층에서는 분기 처리에 대한 로직을 신경쓰지않아도됨 )

고생하셨습니다.

2023-10-30 09:38 UTC, HyukJunJi commented
오늘 한번 해보겠습니다.

2023-10-30 09:39 UTC, merged