wip: 구매 내역 조회 API 개발중 (work in progress)
geezers-io/Stock2U-api pull request #55
Opened 2023-11-07 12:57 UTC by JinkyuByeon

## Type
- [ ] Feature
- [ ] Fix

Implements [issue SU-0](https://geezers-io.atlassian.net/browse/SU-0)

## What & Why

## Checklist
- [ ] 지라 티켓이 있다면 이슈 번호를 매핑하셨나요?

2023-11-07 14:14 UTC, galaxy4276 requested changes

2023-11-07 14:14 UTC, galaxy4276 commented on src/main/java/com/hack/stock2u/order/controller/UserPageController.java
> +    }
이 부분을 RestController 로 교체하고 필요한 데이터 객체를 전달하는 방향으로 변경해보시면 좋을 것 같아요.

관련 레퍼런스 순서대로 확인해보세요!

# 관련 레퍼런스
[@Controller와 @RestController 차이](https://mangkyu.tistory.com/49)
[JSON 이란?](https://codingazua.tistory.com/4)

 > JSON 즉 DTO 객체를 프런트엔드에 RestController 에서 전달하면 JSON 으로 자동으로 변환됩니다. 이 부분  유의하시면서 REST API 서버에서 데이터를 전달하는 것이 어떤 의미인지 파악해보세요.

2023-11-07 14:14 UTC, galaxy4276 commented on src/main/java/com/hack/stock2u/order/dto/OrderItem.java
> +@Entity
각 어노테이션의 의미를 파악하고 꼭 필요한 요소만 사용하도록 하는 것이 좋습니다!
이부분은 오버 엔지니어링된 것 같아요.

다른 DTO 객체 참고 바랍니다!

2023-11-07 14:14 UTC, galaxy4276 commented on src/main/java/com/hack/stock2u/order/dto/OrderItem.java
> +}
해당 클래스는 JPA 의 Entity 를 목적으로 작성된 것으로 보이며 이미
`models/Buyer.java` 로 작성되어있습니다! 혼동하지않게 제거해주셔야할 것 같아요

2023-11-07 14:14 UTC, galaxy4276 commented on src/main/java/com/hack/stock2u/order/repository/Order.java
> +
동일한 엔티티가 여러 개 선언되어 있는 것 같습니다.
Buyer.java 로 이미 작성되어 있습니다!

2023-11-07 14:14 UTC, galaxy4276 commented on src/main/java/com/hack/stock2u/order/repository/OrderRepository.java
> +
Buyer 엔티티 객체 대상으로 수정하시면 될 것 같습니다!

2023-11-07 14:14 UTC, galaxy4276 commented on src/main/java/com/hack/stock2u/order/repository/Order_itemRepository.java
> +}
제거 대상으로 확인됩니다.

2023-11-07 14:14 UTC, galaxy4276 commented on src/main/java/com/hack/stock2u/order/service/ItemService.java
> +}
product 도메인 내부에서 서비스를 사용하시는게 의미가 좀 더 분명한 것 같아요!

2023-11-07 14:14 UTC, galaxy4276 commented on src/main/java/com/hack/stock2u/order/service/OrderService.java
> +}
이 부분 단순 예제로 확인되며 추 후 제거부탁드리겠습니다!

2023-11-07 14:24 UTC, galaxy4276 commented on src/main/java/com/hack/stock2u/order/controller/UserPageController.java
> +    }
또한 Conroller 계층에서 @Trasnactional 은 치명적 이슈가 발생할 수 있습니다.

2023-11-07 14:39 UTC, HyukJunJi commented
저도 헷갈렸던 것처럼 먼저 RestController를 통해 RestAPI에서 GET POST 를 통해 클라이언트와 어떤 데이터를 주고 받는 것을 아는 것이 좋을 것 같습니다. 그리고 차이점도요. 그래야 클라이언트가 어떤 값을 줬을때 그것에 맞는 데이터를 전달해주던가 아니면 특정 응답을 요청해 주는 지를 알 것 같아요. 그 뒤에는 figma를 통해 내 파트에 맞는 부분을 보면서 프론트에서 이 값을 주면, 또는 요청하면 내가 지금 figma에서 보는 페이지를 구성하는데 필요한 데이터들을 프론트에 넘겨줘서 프론트 분들이 내 데이터를 받아서 react로 페이지 하나를 구성할 수 있다고 생각하면 될 것 같아요. 그러긴 위해선 은기님이 작성하신 ERD를 보고 figma를 동시에 보면서 프론트가 원하는 값이 뭐고 그 값을 내가 프론트에 넘겨 주기 위해선 어떻게 java코드로 원하는 값을 프론트에게 넘겨 줄지 고민하는 것이 좋을 것 같아요. 예시 코드들은
# 은기님 product나 seller, user service 로직 보시면 됩니다.

2023-11-08 13:52 UTC, JinkyuByeon commented on src/main/java/com/hack/stock2u/order/repository/OrderRepository.java
> +
수정완료

2023-11-08 13:52 UTC, JinkyuByeon commented on src/main/java/com/hack/stock2u/order/repository/Order.java
> +
확인완료

2023-11-08 13:52 UTC, JinkyuByeon commented on src/main/java/com/hack/stock2u/order/dto/OrderItem.java
> +}
확인완료

2023-11-08 13:53 UTC, JinkyuByeon commented on src/main/java/com/hack/stock2u/order/controller/UserPageController.java
> +    }
Conroller 계층에서 @Trasnactional 은 치명적 이슈 
- 확인완료

2023-11-08 13:53 UTC, JinkyuByeon commented on src/main/java/com/hack/stock2u/order/service/OrderService.java
> +}
확인완료

2023-11-08 19:28 UTC, HyukJunJi commented
추가 적으로 저랑 비슷한 부분이 있어서 저도 제가 맞는 코드는 아니지만 
chat도메인에 api/ReservationApi.class에 
`@Operation(summary = "공통 예약 내역 API", description = "공통으로 예약이 진행중인 내역을 보내주는 API")` 이 부분 참고하시면 좋을 것 같습니다!

2023-11-09 12:10 UTC, galaxy4276 commented on src/main/java/com/hack/stock2u/order/controller/UserPageController.java
> +    public String Buyer (@PathVariable("id") Integer id, Model model, @AuthenticationPrincipal PrincipalDetails principalDetails)
```java
    public String Buyer (@PathVariable("id") Integer id)
```

REST API 구조 상 Model 과 PrincipalDetails 는 받아올 수 없습니다.

2023-11-09 12:10 UTC, galaxy4276 commented on src/main/java/com/hack/stock2u/order/controller/UserPageController.java
> +public class UserPageController implements UserDetails {
`UserDetails` 를 구현하지 않아도 됩니다!

2023-11-09 12:24 UTC, JinkyuByeon commented on src/main/java/com/hack/stock2u/order/controller/UserPageController.java
> +    public String Buyer (@PathVariable("id") Integer id, Model model, @AuthenticationPrincipal PrincipalDetails principalDetails)
오류 계속 떴었는데 감사합니다

2023-11-09 12:24 UTC, JinkyuByeon commented on src/main/java/com/hack/stock2u/order/controller/UserPageController.java
> +public class UserPageController implements UserDetails {
하하.. 한 번 넣어봤습니다..

2023-11-10 18:25 UTC, closed without merging