feat: 판매자 판매 관리 API
geezers-io/Stock2U-api pull request #59
Opened 2023-11-13 16:27 UTC by HyukJunJi

## Type
- [x] Feature
- [ ] Fix

Implements [issue SU-36](https://geezers-io.atlassian.net/browse/SU-36)

## What & Why
![image](https://github.com/geezers-io/Stock2U-api/assets/82084599/2bbf5703-d2be-40d7-8d82-6e2aabe1aef7)
사업자 판매 관리 API 작성했습니다.
체크 박스 요청은 
![image](https://github.com/geezers-io/Stock2U-api/assets/82084599/d49f8433-9bca-486f-9a24-327fab90c65b)
이렇게 작성해봤는데 추후 문제있으면 변경하도록 하겠습니다.
![image](https://github.com/geezers-io/Stock2U-api/assets/82084599/1f0c770e-6955-4543-82f8-82e9511dbd46)
삭제된 예약이랑, 기간 만기된 상품은 안가져오는걸로 했는데 이것도 프론트 이부분 맡으신 분이랑 추후 상의해서 고쳐 나가겠습니다.
![image](https://github.com/geezers-io/Stock2U-api/assets/82084599/685fb0f5-b6f1-4348-b4c5-2eb59dea9c7b)
if문 3개를 사용해서
![image](https://github.com/geezers-io/Stock2U-api/assets/82084599/cefa64b6-312a-414c-b572-35917c93f86a)
필터 조건
1. 모든 데이터(삭제된 예약, 기간 만기된 상품 제외)
2. 제목으로만 검색
3. 예약 상품 보기
4. 판매 상품 보기
5. 제목으로 검색 + 예약 상품 보기
6. 제목으로 검색 + 판매 상품 보기
을 해결 하였습니다.

## Checklist
- [x] 지라 티켓이 있다면 이슈 번호를 매핑하셨나요?

2023-11-13 16:34 UTC, galaxy4276 requested changes
DB에서 한번에 조회하고 필터링하기보다는
DB 에서 가져오는 시점에 필터링하는게 좋아보입니다.

2023-11-13 16:39 UTC, HyukJunJi commented
> DB에서 한번에 조회하고 필터링하기보다는 DB 에서 가져오는 시점에 필터링하는게 좋아보입니다.

![image](https://github.com/geezers-io/Stock2U-api/assets/82084599/f96bffd8-4193-42ff-b1a8-40c46b03e643)
여기만 말씀하시는건가요?
![image](https://github.com/geezers-io/Stock2U-api/assets/82084599/83dcf18e-c4b5-43b1-a4fc-fefee7aee5b1)
아님 이부분 전부다..?

2023-11-13 16:57 UTC, galaxy4276 commented
일반적으로 필터링 이전 DB에서 모든 데이터를 꺼내는 행위는 크나큰 성능 결함으로 이어질 수 있습니다.

`JpaProductRepository`  참고하여 작업 부탁드립니다.
다른 로직도 선 조회 후 필터링을 이용하시는것으로 알고있는데 그부분도 확인해서 수정해주시면 감사드리겠습니다!!

2023-11-13 17:05 UTC, HyukJunJi commented
> 일반적으로 필터링 이전 DB에서 모든 데이터를 꺼내는 행위는 크나큰 성능 결함으로 이어질 수 있습니다.
> 
> `JpaProductRepository` 참고하여 작업 부탁드립니다. 다른 로직도 선 조회 후 필터링을 이용하시는것으로 알고있는데 그부분도 확인해서 수정해주시면 감사드리겠습니다!!

아 이해했습니다. 수정해서 올리겠습니다. 감사합니다~!

2023-11-14 10:15 UTC, JinkyuByeon approved these changes, later dismissed
잘 배우고 있습니다

2023-11-16 18:07 UTC, galaxy4276 commented
넘 고생하셨습니다

2023-11-16 18:07 UTC, galaxy4276 approved these changes

2023-11-16 18:20 UTC, JinkyuByeon approved these changes
잘 보겠습니다

2023-11-17 11:31 UTC, merged